.\" man page create by R# package system.
.TH LINUX 4 2000-01-01 "cpuinfo" "cpuinfo"
.SH NAME
cpuinfo \- \fB/proc/cpuinfo\fR contains information about the processor,
.SH SYNOPSIS
\fIcpuinfo(\fBfile\fR as string = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
\fB/proc/cpuinfo\fR contains information about the processor, 
 the Linux system is running on.
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -
.PP
.SH SEE ALSO
linux
.SH FILES
.PP
Profiler.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
.SH COPYRIGHT
Copyright ©  2020
