.\" man page create by R# package system.
.TH LINUX 4 2000-01-01 "free" "free"
.SH NAME
free \- On Unix-like operating systems, the free command displays the total
.SH SYNOPSIS
\fIfree(\fBfile\fR as string = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
On Unix-like operating systems, the free command displays the total 
 amount of free and used physical and swap memory, and the buffers 
 used by the kernel.
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -
.PP
.SH SEE ALSO
linux
.SH FILES
.PP
Profiler.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
.SH COPYRIGHT
Copyright ©  2020
