.\" man page create by R# package system.
.TH LINUX 4 2000-01-01 "iostat" "iostat"
.SH NAME
iostat \- Report Central Processing Unit (CPU) statistics and input/output
.SH SYNOPSIS
\fIiostat(\fBfile\fR as string = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Report Central Processing Unit (CPU) statistics and input/output 
 statistics for devices, partitions and network filesystems (NFS).
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -
.PP
.SH SEE ALSO
linux
.SH FILES
.PP
Profiler.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
.SH COPYRIGHT
Copyright ©  2020
