.\" man page create by R# package system.
.TH LINUX 4 2000-01-01 "mpstat" "mpstat"
.SH NAME
mpstat \- The mpstat command displays output activities for each available
.SH SYNOPSIS
\fImpstat(\fBfile\fR as string = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
The mpstat command displays output activities for each available 
 processor, processor 0 being the first one. Global average activities 
 among all processors are also reported. The mpstat command can be 
 used both on SMP and UP machines, but in the latter, only global 
 average activities will be printed.
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -
.PP
.SH SEE ALSO
linux
.SH FILES
.PP
Profiler.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
.SH COPYRIGHT
Copyright ©  2020
