.\" man page create by R# package system.
.TH LINUX 4 2000-01-01 "ps" "ps"
.SH NAME
ps \- Get a snapshot of the processes running in your Linux computer with
.SH SYNOPSIS
\fIps(\fBfile\fR as string = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Get a snapshot of the processes running in your Linux computer with 
 the \fBps\fR command. Locate processes by name, user, or even terminal 
 with as much or as little detail as you need.
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -
.PP
.SH SEE ALSO
linux
.SH FILES
.PP
Profiler.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
.SH COPYRIGHT
Copyright ©  2020
