.\" man page create by R# package system.
.TH LINUX 4 2000-01-01 "uptime" "uptime"
.SH NAME
uptime \- On Unix-like operating systems, the uptime command tells
.SH SYNOPSIS
\fIuptime(\fBfile\fR as string = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
On Unix-like operating systems, the uptime command tells 
 you how long the system has been running.
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -
.PP
.SH SEE ALSO
linux
.SH FILES
.PP
Profiler.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
.SH COPYRIGHT
Copyright ©  2020
