.\" man page create by R# package system.
.TH LINUX 4 2000-Jan "os_release" "os_release"
.SH NAME
os_release \- 
.SH SYNOPSIS
\fIos_release(\fBfile\fR as string = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
linux
.SH FILES
.PP
LinuxProfiler.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
